# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
