# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trip',
            new_name='NorthEastAsia',
        ),
    ]
