# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20180517_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Africa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='America',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='China',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Europe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleAsia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oceania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SouthEastAsia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=6)),
                ('agency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
