# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-10 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20180608_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
