# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-10 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itinerary_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
