# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20180922_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
