# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20180922_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='detailed',
            new_name='detail',
        ),
    ]
