# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20180926_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
    ]
